force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Premises__c.field-meta.xml
<CustomField>
    <fullName>Premises__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premises</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <label>Premises</label>
    <nameField>
        <label>Premise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premises__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City where the premises is</description>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country where the premises is</description>
    <label>Country</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Street where the premises is</description>
    <label>Street</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Choose the type of premises when more similar by yours</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>tent</fullName>
            </value>
            <value>
                <fullName>under canopy</fullName>
            </value>
            <value>
                <fullName>castle</fullName>
            </value>
            <value>
                <fullName>farm house</fullName>
            </value>
            <value>
                <fullName>modern banquet hall</fullName>
            </value>
            <value>
                <fullName>other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventController.cls
public with sharing class EventController {
    
    public List<Event__c> listEvents {get; set;}
    
    public EventController() {
        List<Event__c> eventsFromDB = getListEvents();
        listEvents.addAll(eventsFromDB);
    }
    
    @AuraEnabled
    public static List<Event__c> getListEvents() {

        Datetime today = Datetime.now();
        Datetime nextThirtyDays = today.addDays(30);
        String soqlQuery = '';
        soqlQuery += 'SELECT Id, Name, Premises__c,'
                                + ' Premises__r.Name,'
                                + ' Premises__r.City__c,' 
                                + ' Premises__r.Country__c,' 
                                + ' Premises__r.Street__c,'
                                + ' Type__c, StartDateTime__c, EndDateTime__c'
                                + ' FROM Event__c' 
                                + ' WHERE StartDateTime__c > YESTERDAY'
                                + ' AND StartDateTime__c <= NEXT_N_DAYS:30'
                                + ' AND ConfirmEvent__c = true'
                                + ' ORDER BY StartDateTime__c';
        System.debug(soqlQuery);

        List<Event__c> q = (List<Event__c>)Database.query(soqlQuery);

        return q;
    }

    @AuraEnabled
    public static Event__c getInsertedRecord(String nameNewEvent){
        Event__c ev = [SELECT Id, Name, Premises__c, Premises__r.Name, Type__c, StartDateTime__c, EndDateTime__c FROM Event__c WHERE Name = :nameNewEvent LIMIT 1];
        System.debug(ev);
        return ev;
    }
}