force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Premises__c.field-meta.xml
<CustomField>
    <fullName>Premises__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premises</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <label>Premises</label>
    <nameField>
        <label>Premise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/trigger/Premises/PremisesTriggerService.cls
public with sharing class PremisesTriggerService {
    public static void checkIsEventPremise(Map<Id, sObject> premises) {
        List<Premises__c> listPremises = premises.values();
        List<Event__c> eventsByPremise = [SELECT Name FROM Event__c WHERE Premises__c IN :listPremises];

        if (eventsByPremise.size() != 0) {
            premises.values()[0].addError('!!!IMPORTANT. You can\'t delete this Premis. It have future event');
        }
    }
}