force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Premises__c.field-meta.xml
<CustomField>
    <fullName>Premises__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premises</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <label>Premises</label>
    <nameField>
        <label>Premise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/trigger/EventTriggerService.cls
public with sharing class EventTriggerService {
    public static void checkEventsDate(List<Event__c> newEvents) {
        // Map<Id, List<ID>> eventsRelatedPremiseByIdNewEvent = new Map<Id, List<ID>>();
        List<Id> premisesIds = new List<Id>();
        try {
            for (Event__c ev : newEvents) {
                premisesIds.add(ev.Premises__c);
            }
            List<Event__c> eventsFromDB = [SELECT Id, Name, StartDateTime__c, EndDateTime__c, Premises__c FROM Event__c WHERE Premises__c IN :premisesIds];
            
            for(Integer i = 0; i != newEvents.size(); i++) {
                Event__c insertedEvent = newEvents[i];

                for (Event__c item : eventsFromDB) {  
                    if( (insertedEvent.StartDateTime__c > item.StartDateTime__c && insertedEvent.StartDateTime__c < item.EndDateTime__c) 
                     || (insertedEvent.EndDateTime__c > item.StartDateTime__c && insertedEvent.EndDateTime__c < item.EndDateTime__c) 
                     || (item.StartDateTime__c > insertedEvent.StartDateTime__c && item.StartDateTime__c < insertedEvent.EndDateTime__c)
                     || (item.EndDateTime__c > insertedEvent.StartDateTime__c && item.EndDateTime__c < insertedEvent.EndDateTime__c) ) {
                        // insertedEvent.addError(new CalloutException(0, 'You can\'t insert this record.'));
                        insertedEvent.addError('!!!IMPORTANT. The dates is booked. Choose different dates.');
                    }
                }
            }
        } catch (Exception ex) {
            ex.getMessage();
        }
    }
}