force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Premises__c.field-meta.xml
<CustomField>
    <fullName>Premises__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premises</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <label>Premises</label>
    <nameField>
        <label>Premise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premises__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Choose the type of premises when more similar by yours</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>tent</fullName>
            </value>
            <value>
                <fullName>under canopy</fullName>
            </value>
            <value>
                <fullName>castle</fullName>
            </value>
            <value>
                <fullName>farm house</fullName>
            </value>
            <value>
                <fullName>modern banquet hall</fullName>
            </value>
            <value>
                <fullName>other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FullCalendarService.cls
public with sharing class FullCalendarService {

    @AuraEnabled
    public static List<Event__c> fetchAllEvents(){
        List<Event__c> eventList = new List<Event__c>();
        eventList = [SELECT Id, Name, Premises__c, 
                        Premises__r.Name, Type__c, 
                        StartDateTime__c, EndDateTime__c, 
                        IsAllDayEvent__c FROM Event__c LIMIT 100];
        return eventList;
    }
}